### ISSUE TITLE
History is not read properly after restarting mesa run from a model.

### ISSUE THREAD

**Issue by dinilbose** [wmwolf/py_mesa_reader#15]
Thank you very much for providing such a wonderful python tool to interact with MESA files.

Lately, I encountered a problem. I tried to run the re-run the mesa from the one the available model (model_number=1005 , 0.7Gyr) up to a new age of  0.79gyr ( model number 1024).  The history files show the existence of other models like 1034 with the age of 0.81Gyr. But while reading the mesa_reader it only reading up to 0.79 Gyr. It is not showing the other models?

I am attaching the history file for reference? Please let me know how to rectify this.
[history.txt](https://github.com/wmwolf/py_mesa_reader/files/5912038/history.txt)

 issue/

Thank you for your time

**Comment by jschwab** [comment]
This is the expected behavior.  If the model number is non-monotonic, the most recent entries are given precedence.  The output from a restarted run takes precedence over previous output.

**Comment by dinilbose** [comment]
Thank you very for your quick reply. Is there a way I can override this setting in mesa reader and get the full history available in history.data?

**Comment by jschwab** [comment]
If you only want the first part of the history, you could manually delete the final five lines of output associated with the restart. 

The "full history" isn't a meaningful concept here.  When you restart from the middle of a run, you voluntarily discard everything that came after the restart point.  It's too late for MESA to delete this data from the history file (which is why it remains), but the choice of py_mesa_reader to discard it reflects the fact that there is no sensible way to unify the two overlapping pieces of output.

**Comment by dinilbose** [comment]
okay. Thanks
